//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ActivitySet.proto
// Note: requires additional types generated from: RaidGroup.proto
// Note: requires additional types generated from: UnlockTimeGroup.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivitySet")]
  public partial class ActivitySet : global::ProtoBuf.IExtensible
  {
    public ActivitySet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _rewardDesc;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"rewardDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardDesc
    {
      get { return _rewardDesc; }
      set { _rewardDesc = value; }
    }
    private string _startDayDesc;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"startDayDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string startDayDesc
    {
      get { return _startDayDesc; }
      set { _startDayDesc = value; }
    }
    private string _startTimeDesc;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"startTimeDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string startTimeDesc
    {
      get { return _startTimeDesc; }
      set { _startTimeDesc = value; }
    }
    private int _activityTime;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"activityTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityTime
    {
      get { return _activityTime; }
      set { _activityTime = value; }
    }
    private int _raidNum;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"raidNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int raidNum
    {
      get { return _raidNum; }
      set { _raidNum = value; }
    }
    private readonly global::System.Collections.Generic.List<RaidGroup> _raidGroup = new global::System.Collections.Generic.List<RaidGroup>();
    [global::ProtoBuf.ProtoMember(15, Name=@"raidGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RaidGroup> raidGroup
    {
      get { return _raidGroup; }
    }
  
    private int _unlockTimeNum;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"unlockTimeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockTimeNum
    {
      get { return _unlockTimeNum; }
      set { _unlockTimeNum = value; }
    }
    private readonly global::System.Collections.Generic.List<UnlockTimeGroup> _unlockTimeGroup = new global::System.Collections.Generic.List<UnlockTimeGroup>();
    [global::ProtoBuf.ProtoMember(17, Name=@"unlockTimeGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnlockTimeGroup> unlockTimeGroup
    {
      get { return _unlockTimeGroup; }
    }
  
    private string _activityName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"activityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string activityName
    {
      get { return _activityName; }
      set { _activityName = value; }
    }
    private int _unlockTask;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"unlockTask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockTask
    {
      get { return _unlockTask; }
      set { _unlockTask = value; }
    }
    private int _sortNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sortNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sortNum
    {
      get { return _sortNum; }
      set { _sortNum = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private int _activityType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"activityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityType
    {
      get { return _activityType; }
      set { _activityType = value; }
    }
    private int _powerCost;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"powerCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int powerCost
    {
      get { return _powerCost; }
      set { _powerCost = value; }
    }
    private int _unlockLevel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"unlockLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockLevel
    {
      get { return _unlockLevel; }
      set { _unlockLevel = value; }
    }
    private string _activityDesc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"activityDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string activityDesc
    {
      get { return _activityDesc; }
      set { _activityDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}