//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AnabasisPassSet.proto
// Note: requires additional types generated from: PassInfo.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnabasisPassSet")]
  public partial class AnabasisPassSet : global::ProtoBuf.IExtensible
  {
    public AnabasisPassSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _matchPveLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"matchPveLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int matchPveLevel
    {
      get { return _matchPveLevel; }
      set { _matchPveLevel = value; }
    }
    private int _matchDLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"matchDLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int matchDLevel
    {
      get { return _matchDLevel; }
      set { _matchDLevel = value; }
    }
    private int _rewardNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rewardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rewardNum
    {
      get { return _rewardNum; }
      set { _rewardNum = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private readonly global::System.Collections.Generic.List<PassInfo> _pass = new global::System.Collections.Generic.List<PassInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"pass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PassInfo> pass
    {
      get { return _pass; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}