//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AnabasisRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnabasisRewardSet")]
  public partial class AnabasisRewardSet : global::ProtoBuf.IExtensible
  {
    public AnabasisRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _lvCap;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lvCap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lvCap
    {
      get { return _lvCap; }
      set { _lvCap = value; }
    }
    private int _lvLower;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lvLower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lvLower
    {
      get { return _lvLower; }
      set { _lvLower = value; }
    }
    private int _dropID1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dropID1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropID1
    {
      get { return _dropID1; }
      set { _dropID1 = value; }
    }
    private int _dropID2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dropID2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropID2
    {
      get { return _dropID2; }
      set { _dropID2 = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}