//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AnabasisDiffiSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnabasisDiffiSet")]
  public partial class AnabasisDiffiSet : global::ProtoBuf.IExtensible
  {
    public AnabasisDiffiSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _pveType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pveType
    {
      get { return _pveType; }
      set { _pveType = value; }
    }
    private float _hpScale;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hpScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hpScale
    {
      get { return _hpScale; }
      set { _hpScale = value; }
    }
    private float _attackScale;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attackScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attackScale
    {
      get { return _attackScale; }
      set { _attackScale = value; }
    }
    private float _defenceScale;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"defenceScale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float defenceScale
    {
      get { return _defenceScale; }
      set { _defenceScale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}