//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AttriItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttriItem")]
  public partial class AttriItem : global::ProtoBuf.IExtensible
  {
    public AttriItem() {}
    
    private int _AttriType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AttriType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttriType
    {
      get { return _AttriType; }
      set { _AttriType = value; }
    }
    private int _AttriValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AttriValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AttriValue
    {
      get { return _AttriValue; }
      set { _AttriValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}