//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AvatarResSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AvatarResSet")]
  public partial class AvatarResSet : global::ProtoBuf.IExtensible
  {
    public AvatarResSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _resName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resName
    {
      get { return _resName; }
      set { _resName = value; }
    }
    private string _colorFile;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"colorFile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string colorFile
    {
      get { return _colorFile; }
      set { _colorFile = value; }
    }
    private string _iconID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"iconID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconID
    {
      get { return _iconID; }
      set { _iconID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}