//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ClickGoldCountSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClickGoldCountSet")]
  public partial class ClickGoldCountSet : global::ProtoBuf.IExtensible
  {
    public ClickGoldCountSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _goldMulti;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"goldMulti", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldMulti
    {
      get { return _goldMulti; }
      set { _goldMulti = value; }
    }
    private int _diamondMulti;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"diamondMulti", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamondMulti
    {
      get { return _diamondMulti; }
      set { _diamondMulti = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}