//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CommonRewardSet.proto
// Note: requires additional types generated from: RewardItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonRewardSet")]
  public partial class CommonRewardSet : global::ProtoBuf.IExtensible
  {
    public CommonRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _jobChose;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"jobChose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jobChose
    {
      get { return _jobChose; }
      set { _jobChose = value; }
    }
    private int _rewardNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rewardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rewardNum
    {
      get { return _rewardNum; }
      set { _rewardNum = value; }
    }
    private int _showNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"showNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int showNum
    {
      get { return _showNum; }
      set { _showNum = value; }
    }
    private int _upperLimit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"upperLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upperLimit
    {
      get { return _upperLimit; }
      set { _upperLimit = value; }
    }
    private readonly global::System.Collections.Generic.List<RewardItem> _rewardItem = new global::System.Collections.Generic.List<RewardItem>();
    [global::ProtoBuf.ProtoMember(6, Name=@"rewardItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RewardItem> rewardItem
    {
      get { return _rewardItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}