//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CompetitiveHistoryRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompetitiveHistoryRewardSet")]
  public partial class CompetitiveHistoryRewardSet : global::ProtoBuf.IExtensible
  {
    public CompetitiveHistoryRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _idLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"idLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int idLimit
    {
      get { return _idLimit; }
      set { _idLimit = value; }
    }
    private float _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private float _diamond;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private float _competitiveGold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"competitiveGold", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float competitiveGold
    {
      get { return _competitiveGold; }
      set { _competitiveGold = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}