//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ConstantAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConstantAttr")]
  public partial class ConstantAttr : global::ProtoBuf.IExtensible
  {
    public ConstantAttr() {}
    
    private float _attrID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"attrID", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attrID
    {
      get { return _attrID; }
      set { _attrID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}