//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ContinuousSet.proto
// Note: requires additional types generated from: OnlineItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContinuousSet")]
  public partial class ContinuousSet : global::ProtoBuf.IExtensible
  {
    public ContinuousSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _giftID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"giftID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int giftID
    {
      get { return _giftID; }
      set { _giftID = value; }
    }
    private int _rewardNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rewardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rewardNum
    {
      get { return _rewardNum; }
      set { _rewardNum = value; }
    }
    private readonly global::System.Collections.Generic.List<OnlineItem> _rewardItem = new global::System.Collections.Generic.List<OnlineItem>();
    [global::ProtoBuf.ProtoMember(6, Name=@"rewardItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OnlineItem> rewardItem
    {
      get { return _rewardItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}