//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DanbichongzhiSet.proto
// Note: requires additional types generated from: PropGiftAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DanbichongzhiSet")]
  public partial class DanbichongzhiSet : global::ProtoBuf.IExtensible
  {
    public DanbichongzhiSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _quota1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"quota1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quota1
    {
      get { return _quota1; }
      set { _quota1 = value; }
    }
    private int _quota2;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"quota2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quota2
    {
      get { return _quota2; }
      set { _quota2 = value; }
    }
    private int _dropId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"dropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropId
    {
      get { return _dropId; }
      set { _dropId = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<PropGiftAttr> _prop = new global::System.Collections.Generic.List<PropGiftAttr>();
    [global::ProtoBuf.ProtoMember(14, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropGiftAttr> prop
    {
      get { return _prop; }
    }
  
    private int _startYear;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startYear", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startYear
    {
      get { return _startYear; }
      set { _startYear = value; }
    }
    private int _startMonth;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startMonth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startMonth
    {
      get { return _startMonth; }
      set { _startMonth = value; }
    }
    private int _startDay;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"startDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startDay
    {
      get { return _startDay; }
      set { _startDay = value; }
    }
    private int _endYear;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"endYear", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endYear
    {
      get { return _endYear; }
      set { _endYear = value; }
    }
    private int _endMonth;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"endMonth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endMonth
    {
      get { return _endMonth; }
      set { _endMonth = value; }
    }
    private int _endDay;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"endDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endDay
    {
      get { return _endDay; }
      set { _endDay = value; }
    }
    private string _content;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}