//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DragonDesignMapSet.proto
// Note: requires additional types generated from: DragonMapAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DragonDesignMapSet")]
  public partial class DragonDesignMapSet : global::ProtoBuf.IExtensible
  {
    public DragonDesignMapSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _mapName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapName
    {
      get { return _mapName; }
      set { _mapName = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<DragonMapAttr> _attr = new global::System.Collections.Generic.List<DragonMapAttr>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DragonMapAttr> attr
    {
      get { return _attr; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}