//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DragonSet.proto
// Note: requires additional types generated from: DragonAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DragonSet")]
  public partial class DragonSet : global::ProtoBuf.IExtensible
  {
    public DragonSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _minTimes;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"minTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minTimes
    {
      get { return _minTimes; }
      set { _minTimes = value; }
    }
    private int _maxTimes;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"maxTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxTimes
    {
      get { return _maxTimes; }
      set { _maxTimes = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<DragonAttr> _attr = new global::System.Collections.Generic.List<DragonAttr>();
    [global::ProtoBuf.ProtoMember(13, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DragonAttr> attr
    {
      get { return _attr; }
    }
  
    private string _pointName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pointName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pointName
    {
      get { return _pointName; }
      set { _pointName = value; }
    }
    private int _prev;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int prev
    {
      get { return _prev; }
      set { _prev = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _iconid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"iconid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int iconid
    {
      get { return _iconid; }
      set { _iconid = value; }
    }
    private int _openLv;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"openLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int openLv
    {
      get { return _openLv; }
      set { _openLv = value; }
    }
    private int _glod;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"glod", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int glod
    {
      get { return _glod; }
      set { _glod = value; }
    }
    private int _successOdds;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"successOdds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int successOdds
    {
      get { return _successOdds; }
      set { _successOdds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}