//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipComposeSet.proto
// Note: requires additional types generated from: ComposeItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipComposeSet")]
  public partial class EquipComposeSet : global::ProtoBuf.IExtensible
  {
    public EquipComposeSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _dst_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dst_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dst_id
    {
      get { return _dst_id; }
      set { _dst_id = value; }
    }
    private int _composeNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"composeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int composeNum
    {
      get { return _composeNum; }
      set { _composeNum = value; }
    }
    private readonly global::System.Collections.Generic.List<ComposeItem> _materialItems = new global::System.Collections.Generic.List<ComposeItem>();
    [global::ProtoBuf.ProtoMember(7, Name=@"materialItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ComposeItem> materialItems
    {
      get { return _materialItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}