//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipAttrSet.proto
// Note: requires additional types generated from: EquipAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipAttrSet")]
  public partial class EquipAttrSet : global::ProtoBuf.IExtensible
  {
    public EquipAttrSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _combineID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"combineID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int combineID
    {
      get { return _combineID; }
      set { _combineID = value; }
    }
    private int _upgradeLvID;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"upgradeLvID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upgradeLvID
    {
      get { return _upgradeLvID; }
      set { _upgradeLvID = value; }
    }
    private int _canSell;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"canSell", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int canSell
    {
      get { return _canSell; }
      set { _canSell = value; }
    }
    private int _sellPrice;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"sellPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sellPrice
    {
      get { return _sellPrice; }
      set { _sellPrice = value; }
    }
    private int _timeLimit;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"timeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timeLimit
    {
      get { return _timeLimit; }
      set { _timeLimit = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<EquipAttr> _attrData = new global::System.Collections.Generic.List<EquipAttr>();
    [global::ProtoBuf.ProtoMember(16, Name=@"attrData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipAttr> attrData
    {
      get { return _attrData; }
    }
  
    private string _desc;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _iconID;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"iconID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconID
    {
      get { return _iconID; }
      set { _iconID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _jobLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jobLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jobLimit
    {
      get { return _jobLimit; }
      set { _jobLimit = value; }
    }
    private int _equipPos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"equipPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipPos
    {
      get { return _equipPos; }
      set { _equipPos = value; }
    }
    private int _levelLimit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"levelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelLimit
    {
      get { return _levelLimit; }
      set { _levelLimit = value; }
    }
    private int _strengthenLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"strengthenLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strengthenLimit
    {
      get { return _strengthenLimit; }
      set { _strengthenLimit = value; }
    }
    private int _equipColor;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"equipColor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipColor
    {
      get { return _equipColor; }
      set { _equipColor = value; }
    }
    private int _upGradeID;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"upGradeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upGradeID
    {
      get { return _upGradeID; }
      set { _upGradeID = value; }
    }
    private int _strongID;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"strongID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strongID
    {
      get { return _strongID; }
      set { _strongID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}