//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipDecomposeSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipDecomposeSet")]
  public partial class EquipDecomposeSet : global::ProtoBuf.IExtensible
  {
    public EquipDecomposeSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _material_id1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"material_id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int material_id1
    {
      get { return _material_id1; }
      set { _material_id1 = value; }
    }
    private int _num1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num1
    {
      get { return _num1; }
      set { _num1 = value; }
    }
    private int _material_id2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"material_id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int material_id2
    {
      get { return _material_id2; }
      set { _material_id2 = value; }
    }
    private int _num2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num2
    {
      get { return _num2; }
      set { _num2 = value; }
    }
    private int _material_id3;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"material_id3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int material_id3
    {
      get { return _material_id3; }
      set { _material_id3 = value; }
    }
    private int _num3;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"num3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num3
    {
      get { return _num3; }
      set { _num3 = value; }
    }
    private int _material_id4;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"material_id4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int material_id4
    {
      get { return _material_id4; }
      set { _material_id4 = value; }
    }
    private int _num4;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"num4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num4
    {
      get { return _num4; }
      set { _num4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}