//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FashionDressSet.proto
// Note: requires additional types generated from: ShiZhuangAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FashionDressSet")]
  public partial class FashionDressSet : global::ProtoBuf.IExtensible
  {
    public FashionDressSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _fashionDressName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fashionDressName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fashionDressName
    {
      get { return _fashionDressName; }
      set { _fashionDressName = value; }
    }
    private int _jobLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jobLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jobLimit
    {
      get { return _jobLimit; }
      set { _jobLimit = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private int _modelId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"modelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int modelId
    {
      get { return _modelId; }
      set { _modelId = value; }
    }
    private int _conditionType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"conditionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int conditionType
    {
      get { return _conditionType; }
      set { _conditionType = value; }
    }
    private int _conditionValue;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"conditionValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int conditionValue
    {
      get { return _conditionValue; }
      set { _conditionValue = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<ShiZhuangAttr> _attr = new global::System.Collections.Generic.List<ShiZhuangAttr>();
    [global::ProtoBuf.ProtoMember(9, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ShiZhuangAttr> attr
    {
      get { return _attr; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}