//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightNumUp.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightNumUp")]
  public partial class FightNumUp : global::ProtoBuf.IExtensible
  {
    public FightNumUp() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _title;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title
    {
      get { return _title; }
      set { _title = value; }
    }
    private int _skill;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill
    {
      get { return _skill; }
      set { _skill = value; }
    }
    private int _cdSkill;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"cdSkill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cdSkill
    {
      get { return _cdSkill; }
      set { _cdSkill = value; }
    }
    private int _equipQuality;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"equipQuality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipQuality
    {
      get { return _equipQuality; }
      set { _equipQuality = value; }
    }
    private int _equipUpgradeStar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"equipUpgradeStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipUpgradeStar
    {
      get { return _equipUpgradeStar; }
      set { _equipUpgradeStar = value; }
    }
    private int _equipLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"equipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipLevel
    {
      get { return _equipLevel; }
      set { _equipLevel = value; }
    }
    private int _minggeNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"minggeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minggeNum
    {
      get { return _minggeNum; }
      set { _minggeNum = value; }
    }
    private int _dragonNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dragonNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dragonNum
    {
      get { return _dragonNum; }
      set { _dragonNum = value; }
    }
    private int _machaiPlayNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"machaiPlayNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int machaiPlayNum
    {
      get { return _machaiPlayNum; }
      set { _machaiPlayNum = value; }
    }
    private int _machaiTrainNum;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"machaiTrainNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int machaiTrainNum
    {
      get { return _machaiTrainNum; }
      set { _machaiTrainNum = value; }
    }
    private int _machaiQuality;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"machaiQuality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int machaiQuality
    {
      get { return _machaiQuality; }
      set { _machaiQuality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}