//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightNumLevel.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightNumLevel")]
  public partial class FightNumLevel : global::ProtoBuf.IExtensible
  {
    public FightNumLevel() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Up;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Up", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Up
    {
      get { return _Up; }
      set { _Up = value; }
    }
    private int _Down;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Down", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Down
    {
      get { return _Down; }
      set { _Down = value; }
    }
    private string _Level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}