//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightRewardSet")]
  public partial class FightRewardSet : global::ProtoBuf.IExtensible
  {
    public FightRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _levelLow;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"levelLow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelLow
    {
      get { return _levelLow; }
      set { _levelLow = value; }
    }
    private int _levelUp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"levelUp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelUp
    {
      get { return _levelUp; }
      set { _levelUp = value; }
    }
    private int _diamond1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"diamond1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond1
    {
      get { return _diamond1; }
      set { _diamond1 = value; }
    }
    private int _gold1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gold1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold1
    {
      get { return _gold1; }
      set { _gold1 = value; }
    }
    private int _drop1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"drop1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int drop1
    {
      get { return _drop1; }
      set { _drop1 = value; }
    }
    private int _diamond2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"diamond2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond2
    {
      get { return _diamond2; }
      set { _diamond2 = value; }
    }
    private int _gold2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"gold2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold2
    {
      get { return _gold2; }
      set { _gold2 = value; }
    }
    private int _drop2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"drop2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int drop2
    {
      get { return _drop2; }
      set { _drop2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}