//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildStoreSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildStoreSet")]
  public partial class GuildStoreSet : global::ProtoBuf.IExtensible
  {
    public GuildStoreSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _DropID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DropID
    {
      get { return _DropID; }
      set { _DropID = value; }
    }
    private int _ItemID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private int _InitialCount;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"InitialCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int InitialCount
    {
      get { return _InitialCount; }
      set { _InitialCount = value; }
    }
    private int _ArisesProbability;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ArisesProbability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ArisesProbability
    {
      get { return _ArisesProbability; }
      set { _ArisesProbability = value; }
    }
    private int _DonateCost;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"DonateCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DonateCost
    {
      get { return _DonateCost; }
      set { _DonateCost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}