//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildDonateSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildDonateSet")]
  public partial class GuildDonateSet : global::ProtoBuf.IExtensible
  {
    public GuildDonateSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _personalDonate;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"personalDonate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int personalDonate
    {
      get { return _personalDonate; }
      set { _personalDonate = value; }
    }
    private int _guildDonate;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"guildDonate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int guildDonate
    {
      get { return _guildDonate; }
      set { _guildDonate = value; }
    }
    private int _donateTimes;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"donateTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int donateTimes
    {
      get { return _donateTimes; }
      set { _donateTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}