//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildWorkshopSkillSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildWorkshopSkillSet")]
  public partial class GuildWorkshopSkillSet : global::ProtoBuf.IExtensible
  {
    public GuildWorkshopSkillSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _descID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"descID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int descID
    {
      get { return _descID; }
      set { _descID = value; }
    }
    private int _SkillId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }
    private int _SkillValue;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SkillValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillValue
    {
      get { return _SkillValue; }
      set { _SkillValue = value; }
    }
    private int _Diamond;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}