//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GuildLevelSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildLevelSet")]
  public partial class GuildLevelSet : global::ProtoBuf.IExtensible
  {
    public GuildLevelSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _donation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"donation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int donation
    {
      get { return _donation; }
      set { _donation = value; }
    }
    private int _maxPerson;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"maxPerson", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxPerson
    {
      get { return _maxPerson; }
      set { _maxPerson = value; }
    }
    private int _viceChairman;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"viceChairman", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int viceChairman
    {
      get { return _viceChairman; }
      set { _viceChairman = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}