//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LieMingInfoSet.proto
// Note: requires additional types generated from: MinggeItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LieMingInfoSet")]
  public partial class LieMingInfoSet : global::ProtoBuf.IExtensible
  {
    public LieMingInfoSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _minggeNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"minggeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minggeNum
    {
      get { return _minggeNum; }
      set { _minggeNum = value; }
    }
    private readonly global::System.Collections.Generic.List<MinggeItem> _minggeItem = new global::System.Collections.Generic.List<MinggeItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"minggeItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MinggeItem> minggeItem
    {
      get { return _minggeItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}