//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MachaiShengxingriRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachaiShengxingriRewardSet")]
  public partial class MachaiShengxingriRewardSet : global::ProtoBuf.IExtensible
  {
    public MachaiShengxingriRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _freeNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"freeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int freeNum
    {
      get { return _freeNum; }
      set { _freeNum = value; }
    }
    private int _num1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num1
    {
      get { return _num1; }
      set { _num1 = value; }
    }
    private int _num2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"num2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num2
    {
      get { return _num2; }
      set { _num2 = value; }
    }
    private int _num3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num3
    {
      get { return _num3; }
      set { _num3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}