//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiStarUpRequireSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiStarUpRequireSet")]
  public partial class MaChaiStarUpRequireSet : global::ProtoBuf.IExtensible
  {
    public MaChaiStarUpRequireSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _soulStoneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"soulStoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soulStoneId
    {
      get { return _soulStoneId; }
      set { _soulStoneId = value; }
    }
    private int _tmpSoulStoneId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tmpSoulStoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tmpSoulStoneId
    {
      get { return _tmpSoulStoneId; }
      set { _tmpSoulStoneId = value; }
    }
    private int _soulStoneCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"soulStoneCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int soulStoneCount
    {
      get { return _soulStoneCount; }
      set { _soulStoneCount = value; }
    }
    private int _levelLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"levelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelLimit
    {
      get { return _levelLimit; }
      set { _levelLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}