//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiEquipSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiEquipSet")]
  public partial class MaChaiEquipSet : global::ProtoBuf.IExtensible
  {
    public MaChaiEquipSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _chip2_num;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"chip2_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip2_num
    {
      get { return _chip2_num; }
      set { _chip2_num = value; }
    }
    private int _chip3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"chip3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip3
    {
      get { return _chip3; }
      set { _chip3 = value; }
    }
    private int _chip3_num;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"chip3_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip3_num
    {
      get { return _chip3_num; }
      set { _chip3_num = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _requiredLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"requiredLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int requiredLevel
    {
      get { return _requiredLevel; }
      set { _requiredLevel = value; }
    }
    private int _chip1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"chip1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip1
    {
      get { return _chip1; }
      set { _chip1 = value; }
    }
    private int _chip1_num;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"chip1_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip1_num
    {
      get { return _chip1_num; }
      set { _chip1_num = value; }
    }
    private int _chip2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"chip2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chip2
    {
      get { return _chip2; }
      set { _chip2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}