//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiBuffSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiBuffSet")]
  public partial class MaChaiBuffSet : global::ProtoBuf.IExtensible
  {
    public MaChaiBuffSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private float _tempLast;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"tempLast", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float tempLast
    {
      get { return _tempLast; }
      set { _tempLast = value; }
    }
    private int _fc;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"fc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fc
    {
      get { return _fc; }
      set { _fc = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _conid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"conid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string conid
    {
      get { return _conid; }
      set { _conid = value; }
    }
    private int _forEverID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"forEverID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int forEverID
    {
      get { return _forEverID; }
      set { _forEverID = value; }
    }
    private int _forEvervalue;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"forEvervalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int forEvervalue
    {
      get { return _forEvervalue; }
      set { _forEvervalue = value; }
    }
    private int _tempID;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"tempID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempID
    {
      get { return _tempID; }
      set { _tempID = value; }
    }
    private float _tempvalue;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"tempvalue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float tempvalue
    {
      get { return _tempvalue; }
      set { _tempvalue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}