//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MachaiShengxingriSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachaiShengxingriSet")]
  public partial class MachaiShengxingriSet : global::ProtoBuf.IExtensible
  {
    public MachaiShengxingriSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _nextId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nextId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextId
    {
      get { return _nextId; }
      set { _nextId = value; }
    }
    private int _machaiId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"machaiId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int machaiId
    {
      get { return _machaiId; }
      set { _machaiId = value; }
    }
    private string _halfBodyIcon;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"halfBodyIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string halfBodyIcon
    {
      get { return _halfBodyIcon; }
      set { _halfBodyIcon = value; }
    }
    private string _fragIcon;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fragIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string fragIcon
    {
      get { return _fragIcon; }
      set { _fragIcon = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private string _machaiName;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"machaiName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string machaiName
    {
      get { return _machaiName; }
      set { _machaiName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}