//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiSet")]
  public partial class MaChaiSet : global::ProtoBuf.IExtensible
  {
    public MaChaiSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _skill2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"skill2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill2
    {
      get { return _skill2; }
      set { _skill2 = value; }
    }
    private int _propId;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"propId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int propId
    {
      get { return _propId; }
      set { _propId = value; }
    }
    private int _propCount;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"propCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int propCount
    {
      get { return _propCount; }
      set { _propCount = value; }
    }
    private float _scale;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private int _dodge;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private int _hit;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _crit;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit
    {
      get { return _crit; }
      set { _crit = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _critAttack;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"critAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int critAttack
    {
      get { return _critAttack; }
      set { _critAttack = value; }
    }
    private int _tough;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"tough", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tough
    {
      get { return _tough; }
      set { _tough = value; }
    }
    private int _damageReduce;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"damageReduce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damageReduce
    {
      get { return _damageReduce; }
      set { _damageReduce = value; }
    }
    private int _damageAdd;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"damageAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damageAdd
    {
      get { return _damageAdd; }
      set { _damageAdd = value; }
    }
    private string _ai;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"ai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ai
    {
      get { return _ai; }
      set { _ai = value; }
    }
    private int _additionalFc;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"additionalFc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int additionalFc
    {
      get { return _additionalFc; }
      set { _additionalFc = value; }
    }
    private int _isShow;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _star;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private int _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _trainLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"trainLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trainLevel
    {
      get { return _trainLevel; }
      set { _trainLevel = value; }
    }
    private int _avatarID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"avatarID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int avatarID
    {
      get { return _avatarID; }
      set { _avatarID = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _skill1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"skill1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill1
    {
      get { return _skill1; }
      set { _skill1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}