//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiStarUpProperSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiStarUpProperSet")]
  public partial class MaChaiStarUpProperSet : global::ProtoBuf.IExtensible
  {
    public MaChaiStarUpProperSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private float _hpGrow;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hpGrow", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float hpGrow
    {
      get { return _hpGrow; }
      set { _hpGrow = value; }
    }
    private float _attackGrow;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"attackGrow", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attackGrow
    {
      get { return _attackGrow; }
      set { _attackGrow = value; }
    }
    private float _defenceGrow;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"defenceGrow", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float defenceGrow
    {
      get { return _defenceGrow; }
      set { _defenceGrow = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}