//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MaChaiTrainRequireSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaChaiTrainRequireSet")]
  public partial class MaChaiTrainRequireSet : global::ProtoBuf.IExtensible
  {
    public MaChaiTrainRequireSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _currentAttack;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"currentAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentAttack
    {
      get { return _currentAttack; }
      set { _currentAttack = value; }
    }
    private int _currentDefense;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"currentDefense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentDefense
    {
      get { return _currentDefense; }
      set { _currentDefense = value; }
    }
    private int _totalHp;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"totalHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalHp
    {
      get { return _totalHp; }
      set { _totalHp = value; }
    }
    private int _tatalAttack;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"tatalAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tatalAttack
    {
      get { return _tatalAttack; }
      set { _tatalAttack = value; }
    }
    private int _totalDefense;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"totalDefense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalDefense
    {
      get { return _totalDefense; }
      set { _totalDefense = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _item1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item1
    {
      get { return _item1; }
      set { _item1 = value; }
    }
    private int _item2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"item2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item2
    {
      get { return _item2; }
      set { _item2 = value; }
    }
    private int _item3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"item3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item3
    {
      get { return _item3; }
      set { _item3 = value; }
    }
    private int _item4;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"item4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item4
    {
      get { return _item4; }
      set { _item4 = value; }
    }
    private int _item5;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"item5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item5
    {
      get { return _item5; }
      set { _item5 = value; }
    }
    private int _item6;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"item6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item6
    {
      get { return _item6; }
      set { _item6 = value; }
    }
    private int _currentHp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"currentHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentHp
    {
      get { return _currentHp; }
      set { _currentHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}