//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MallScoreSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallScoreSet")]
  public partial class MallScoreSet : global::ProtoBuf.IExtensible
  {
    public MallScoreSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _label;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int label
    {
      get { return _label; }
      set { _label = value; }
    }
    private int _salePirce;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"salePirce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int salePirce
    {
      get { return _salePirce; }
      set { _salePirce = value; }
    }
    private int _minLevel;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    private int _maxLevel;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    private int _vipLevel;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private int _dropId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropId
    {
      get { return _dropId; }
      set { _dropId = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _probability;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability
    {
      get { return _probability; }
      set { _probability = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}