//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MapSet.proto
// Note: requires additional types generated from: UnLockCond.proto
// Note: requires additional types generated from: MonsterGroup.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapSet")]
  public partial class MapSet : global::ProtoBuf.IExtensible
  {
    public MapSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _bornRightPosX;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"bornRightPosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bornRightPosX
    {
      get { return _bornRightPosX; }
      set { _bornRightPosX = value; }
    }
    private int _bornRightPosY;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"bornRightPosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bornRightPosY
    {
      get { return _bornRightPosY; }
      set { _bornRightPosY = value; }
    }
    private string _mapAI;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"mapAI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapAI
    {
      get { return _mapAI; }
      set { _mapAI = value; }
    }
    private int _timeLimit;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"timeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timeLimit
    {
      get { return _timeLimit; }
      set { _timeLimit = value; }
    }
    private int _raidGatewayPosX;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"raidGatewayPosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int raidGatewayPosX
    {
      get { return _raidGatewayPosX; }
      set { _raidGatewayPosX = value; }
    }
    private int _raidGatewayPosY;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"raidGatewayPosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int raidGatewayPosY
    {
      get { return _raidGatewayPosY; }
      set { _raidGatewayPosY = value; }
    }
    private int _mapGatewayPosX;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"mapGatewayPosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapGatewayPosX
    {
      get { return _mapGatewayPosX; }
      set { _mapGatewayPosX = value; }
    }
    private int _mapGatewayPosY;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"mapGatewayPosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapGatewayPosY
    {
      get { return _mapGatewayPosY; }
      set { _mapGatewayPosY = value; }
    }
    private string _mapPath;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"mapPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapPath
    {
      get { return _mapPath; }
      set { _mapPath = value; }
    }
    private int _powerCost;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"powerCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int powerCost
    {
      get { return _powerCost; }
      set { _powerCost = value; }
    }
    private int _mapType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mapType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapType
    {
      get { return _mapType; }
      set { _mapType = value; }
    }
    private int _recommendFightCap;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"recommendFightCap", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recommendFightCap
    {
      get { return _recommendFightCap; }
      set { _recommendFightCap = value; }
    }
    private int _startCondMinPlayer;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"startCondMinPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startCondMinPlayer
    {
      get { return _startCondMinPlayer; }
      set { _startCondMinPlayer = value; }
    }
    private int _startCondMaxPlayer;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"startCondMaxPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startCondMaxPlayer
    {
      get { return _startCondMaxPlayer; }
      set { _startCondMaxPlayer = value; }
    }
    private int _enterTimeLimit;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"enterTimeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enterTimeLimit
    {
      get { return _enterTimeLimit; }
      set { _enterTimeLimit = value; }
    }
    private int _coolDown;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"coolDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coolDown
    {
      get { return _coolDown; }
      set { _coolDown = value; }
    }
    private int _resetTime;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"resetTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resetTime
    {
      get { return _resetTime; }
      set { _resetTime = value; }
    }
    private int _lastTime;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"lastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastTime
    {
      get { return _lastTime; }
      set { _lastTime = value; }
    }
    private int _unlockCondNum;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"unlockCondNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockCondNum
    {
      get { return _unlockCondNum; }
      set { _unlockCondNum = value; }
    }
    private int _condRelation;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"condRelation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int condRelation
    {
      get { return _condRelation; }
      set { _condRelation = value; }
    }
    private readonly global::System.Collections.Generic.List<UnLockCond> _unlockCond = new global::System.Collections.Generic.List<UnLockCond>();
    [global::ProtoBuf.ProtoMember(29, Name=@"unlockCond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnLockCond> unlockCond
    {
      get { return _unlockCond; }
    }
  
    private int _storyIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"storyIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int storyIndex
    {
      get { return _storyIndex; }
      set { _storyIndex = value; }
    }
    private int _dropId;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"dropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropId
    {
      get { return _dropId; }
      set { _dropId = value; }
    }
    private int _bossId;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"bossId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bossId
    {
      get { return _bossId; }
      set { _bossId = value; }
    }
    private int _monsterListNum;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"monsterListNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monsterListNum
    {
      get { return _monsterListNum; }
      set { _monsterListNum = value; }
    }
    private readonly global::System.Collections.Generic.List<MonsterGroup> _monsterList = new global::System.Collections.Generic.List<MonsterGroup>();
    [global::ProtoBuf.ProtoMember(33, Name=@"monsterList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MonsterGroup> monsterList
    {
      get { return _monsterList; }
    }
  
    private int _mountGroupNum;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"mountGroupNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mountGroupNum
    {
      get { return _mountGroupNum; }
      set { _mountGroupNum = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _mountGroup = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(35, Name=@"mountGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> mountGroup
    {
      get { return _mountGroup; }
    }
  
    private string _mapName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mapName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapName
    {
      get { return _mapName; }
      set { _mapName = value; }
    }
    private string _mapDesc;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mapDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mapDesc
    {
      get { return _mapDesc; }
      set { _mapDesc = value; }
    }
    private string _IconID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"IconID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IconID
    {
      get { return _IconID; }
      set { _IconID = value; }
    }
    private int _backgroudMusic;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"backgroudMusic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int backgroudMusic
    {
      get { return _backgroudMusic; }
      set { _backgroudMusic = value; }
    }
    private int _bornPosX;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"bornPosX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bornPosX
    {
      get { return _bornPosX; }
      set { _bornPosX = value; }
    }
    private int _bornPosY;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"bornPosY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bornPosY
    {
      get { return _bornPosY; }
      set { _bornPosY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}