//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MinggeItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinggeItem")]
  public partial class MinggeItem : global::ProtoBuf.IExtensible
  {
    public MinggeItem() {}
    
    private int _minggeID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"minggeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minggeID
    {
      get { return _minggeID; }
      set { _minggeID = value; }
    }
    private int _minggeProbability;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"minggeProbability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minggeProbability
    {
      get { return _minggeProbability; }
      set { _minggeProbability = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}