//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MinggeSet.proto
// Note: requires additional types generated from: AttriItem.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinggeSet")]
  public partial class MinggeSet : global::ProtoBuf.IExtensible
  {
    public MinggeSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _upgradeLevelExp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"upgradeLevelExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upgradeLevelExp
    {
      get { return _upgradeLevelExp; }
      set { _upgradeLevelExp = value; }
    }
    private int _devourExp;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"devourExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int devourExp
    {
      get { return _devourExp; }
      set { _devourExp = value; }
    }
    private int _upgradeExp;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"upgradeExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upgradeExp
    {
      get { return _upgradeExp; }
      set { _upgradeExp = value; }
    }
    private int _upgradeID;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"upgradeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upgradeID
    {
      get { return _upgradeID; }
      set { _upgradeID = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private int _attriNum;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"attriNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attriNum
    {
      get { return _attriNum; }
      set { _attriNum = value; }
    }
    private readonly global::System.Collections.Generic.List<AttriItem> _attri = new global::System.Collections.Generic.List<AttriItem>();
    [global::ProtoBuf.ProtoMember(16, Name=@"attri", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttriItem> attri
    {
      get { return _attri; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _equipType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"equipType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int equipType
    {
      get { return _equipType; }
      set { _equipType = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _quality;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _usedLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"usedLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int usedLevel
    {
      get { return _usedLevel; }
      set { _usedLevel = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _prof;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"prof", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int prof
    {
      get { return _prof; }
      set { _prof = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}