//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterSet")]
  public partial class MonsterSet : global::ProtoBuf.IExtensible
  {
    public MonsterSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _dodge;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private float _isBigMode;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"isBigMode", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float isBigMode
    {
      get { return _isBigMode; }
      set { _isBigMode = value; }
    }
    private int _damageSub;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"damageSub", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damageSub
    {
      get { return _damageSub; }
      set { _damageSub = value; }
    }
    private int _damageAdd;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"damageAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damageAdd
    {
      get { return _damageAdd; }
      set { _damageAdd = value; }
    }
    private int _active;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"active", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int active
    {
      get { return _active; }
      set { _active = value; }
    }
    private string _aiName;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"aiName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string aiName
    {
      get { return _aiName; }
      set { _aiName = value; }
    }
    private string _banShenXiang;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"banShenXiang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string banShenXiang
    {
      get { return _banShenXiang; }
      set { _banShenXiang = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _talkId;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"talkId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int talkId
    {
      get { return _talkId; }
      set { _talkId = value; }
    }
    private string _monsterName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"monsterName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string monsterName
    {
      get { return _monsterName; }
      set { _monsterName = value; }
    }
    private int _avatarId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatarId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int avatarId
    {
      get { return _avatarId; }
      set { _avatarId = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _attack;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }
    private int _defence;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defence
    {
      get { return _defence; }
      set { _defence = value; }
    }
    private int _crit;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int crit
    {
      get { return _crit; }
      set { _crit = value; }
    }
    private int _tough;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"tough", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tough
    {
      get { return _tough; }
      set { _tough = value; }
    }
    private int _hit;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}