//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MusicResSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MusicResSet")]
  public partial class MusicResSet : global::ProtoBuf.IExtensible
  {
    public MusicResSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _musicEvent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"musicEvent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string musicEvent
    {
      get { return _musicEvent; }
      set { _musicEvent = value; }
    }
    private int _isBGM;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isBGM", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isBGM
    {
      get { return _isBGM; }
      set { _isBGM = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}