//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NewBieSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewBieSet")]
  public partial class NewBieSet : global::ProtoBuf.IExtensible
  {
    public NewBieSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _preID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"preID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int preID
    {
      get { return _preID; }
      set { _preID = value; }
    }
    private int _unlockType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"unlockType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockType
    {
      get { return _unlockType; }
      set { _unlockType = value; }
    }
    private int _unlockParam;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"unlockParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockParam
    {
      get { return _unlockParam; }
      set { _unlockParam = value; }
    }
    private string _aiName;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"aiName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string aiName
    {
      get { return _aiName; }
      set { _aiName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}