//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerTitleSet.proto
// Note: requires additional types generated from: TitleAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerTitleSet")]
  public partial class PlayerTitleSet : global::ProtoBuf.IExtensible
  {
    public PlayerTitleSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _ActivateID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActivateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ActivateID
    {
      get { return _ActivateID; }
      set { _ActivateID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _conditions;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"conditions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string conditions
    {
      get { return _conditions; }
      set { _conditions = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<TitleAttr> _attrData = new global::System.Collections.Generic.List<TitleAttr>();
    [global::ProtoBuf.ProtoMember(8, Name=@"attrData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TitleAttr> attrData
    {
      get { return _attrData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}