//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: QuestSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestSet")]
  public partial class QuestSet : global::ProtoBuf.IExtensible
  {
    public QuestSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _data2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"data2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data2
    {
      get { return _data2; }
      set { _data2 = value; }
    }
    private int _data3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"data3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data3
    {
      get { return _data3; }
      set { _data3 = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _taskDest;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"taskDest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string taskDest
    {
      get { return _taskDest; }
      set { _taskDest = value; }
    }
    private string _recvDialogue;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"recvDialogue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string recvDialogue
    {
      get { return _recvDialogue; }
      set { _recvDialogue = value; }
    }
    private string _playerRecvDialogue;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"playerRecvDialogue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerRecvDialogue
    {
      get { return _playerRecvDialogue; }
      set { _playerRecvDialogue = value; }
    }
    private string _playerCompleteDialogue;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"playerCompleteDialogue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerCompleteDialogue
    {
      get { return _playerCompleteDialogue; }
      set { _playerCompleteDialogue = value; }
    }
    private string _completeDialogue;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"completeDialogue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string completeDialogue
    {
      get { return _completeDialogue; }
      set { _completeDialogue = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _diamond;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _liemingGold;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"liemingGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int liemingGold
    {
      get { return _liemingGold; }
      set { _liemingGold = value; }
    }
    private int _dragonSoul;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"dragonSoul", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dragonSoul
    {
      get { return _dragonSoul; }
      set { _dragonSoul = value; }
    }
    private int _dropId;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"dropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropId
    {
      get { return _dropId; }
      set { _dropId = value; }
    }
    private int _flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _recvLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"recvLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recvLevel
    {
      get { return _recvLevel; }
      set { _recvLevel = value; }
    }
    private int _recvNPC;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"recvNPC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recvNPC
    {
      get { return _recvNPC; }
      set { _recvNPC = value; }
    }
    private int _complateNPC;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"complateNPC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int complateNPC
    {
      get { return _complateNPC; }
      set { _complateNPC = value; }
    }
    private int _prevId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"prevId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int prevId
    {
      get { return _prevId; }
      set { _prevId = value; }
    }
    private int _data1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"data1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data1
    {
      get { return _data1; }
      set { _data1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}