//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RaidRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidRewardSet")]
  public partial class RaidRewardSet : global::ProtoBuf.IExtensible
  {
    public RaidRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _commonRewardID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"commonRewardID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int commonRewardID
    {
      get { return _commonRewardID; }
      set { _commonRewardID = value; }
    }
    private string _rewardDesc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rewardDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string rewardDesc
    {
      get { return _rewardDesc; }
      set { _rewardDesc = value; }
    }
    private int _minGold;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"minGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minGold
    {
      get { return _minGold; }
      set { _minGold = value; }
    }
    private int _maxGold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"maxGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxGold
    {
      get { return _maxGold; }
      set { _maxGold = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _dragonSoul;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dragonSoul", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dragonSoul
    {
      get { return _dragonSoul; }
      set { _dragonSoul = value; }
    }
    private int _liemingGold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"liemingGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int liemingGold
    {
      get { return _liemingGold; }
      set { _liemingGold = value; }
    }
    private int _specialRewardID;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"specialRewardID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int specialRewardID
    {
      get { return _specialRewardID; }
      set { _specialRewardID = value; }
    }
    private int _maxCommonRewardNum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"maxCommonRewardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxCommonRewardNum
    {
      get { return _maxCommonRewardNum; }
      set { _maxCommonRewardNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}