//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RaidGroup.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RaidGroup")]
  public partial class RaidGroup : global::ProtoBuf.IExtensible
  {
    public RaidGroup() {}
    
    private int _raidId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"raidId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int raidId
    {
      get { return _raidId; }
      set { _raidId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}