//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RobotSet.proto
// Note: requires additional types generated from: AttrList.proto
// Note: requires additional types generated from: SkillList.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotSet")]
  public partial class RobotSet : global::ProtoBuf.IExtensible
  {
    public RobotSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _camp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp; }
      set { _camp = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private readonly global::System.Collections.Generic.List<AttrList> _attrData = new global::System.Collections.Generic.List<AttrList>();
    [global::ProtoBuf.ProtoMember(12, Name=@"attrData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttrList> attrData
    {
      get { return _attrData; }
    }
  
    private int _skillNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"skillNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillNum
    {
      get { return _skillNum; }
      set { _skillNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SkillList> _skillData = new global::System.Collections.Generic.List<SkillList>();
    [global::ProtoBuf.ProtoMember(14, Name=@"skillData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillList> skillData
    {
      get { return _skillData; }
    }
  
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _posX;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _job;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int job
    {
      get { return _job; }
      set { _job = value; }
    }
    private int _avataId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"avataId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int avataId
    {
      get { return _avataId; }
      set { _avataId = value; }
    }
    private int _wingId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wingId
    {
      get { return _wingId; }
      set { _wingId = value; }
    }
    private float _fc;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"fc", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float fc
    {
      get { return _fc; }
      set { _fc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}