//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ServerSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerSet")]
  public partial class ServerSet : global::ProtoBuf.IExtensible
  {
    public ServerSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _ServerName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ServerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerName
    {
      get { return _ServerName; }
      set { _ServerName = value; }
    }
    private string _District;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"District", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string District
    {
      get { return _District; }
      set { _District = value; }
    }
    private int _Status;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private string _IPAddr;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"IPAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IPAddr
    {
      get { return _IPAddr; }
      set { _IPAddr = value; }
    }
    private int _Port;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Port
    {
      get { return _Port; }
      set { _Port = value; }
    }
    private int _GmPort;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"GmPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int GmPort
    {
      get { return _GmPort; }
      set { _GmPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}