//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ShopUseDiamondSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopUseDiamondSet")]
  public partial class ShopUseDiamondSet : global::ProtoBuf.IExtensible
  {
    public ShopUseDiamondSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _areneCost;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"areneCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areneCost
    {
      get { return _areneCost; }
      set { _areneCost = value; }
    }
    private int _donateCost;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"donateCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int donateCost
    {
      get { return _donateCost; }
      set { _donateCost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}