//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SignRewardSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignRewardSet")]
  public partial class SignRewardSet : global::ProtoBuf.IExtensible
  {
    public SignRewardSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _RewardId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RewardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RewardId
    {
      get { return _RewardId; }
      set { _RewardId = value; }
    }
    private int _RewardNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RewardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RewardNum
    {
      get { return _RewardNum; }
      set { _RewardNum = value; }
    }
    private int _GoldNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"GoldNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int GoldNum
    {
      get { return _GoldNum; }
      set { _GoldNum = value; }
    }
    private int _DiamonNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DiamonNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DiamonNum
    {
      get { return _DiamonNum; }
      set { _DiamonNum = value; }
    }
    private int _Strength;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Strength
    {
      get { return _Strength; }
      set { _Strength = value; }
    }
    private int _VIPCondition;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"VIPCondition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VIPCondition
    {
      get { return _VIPCondition; }
      set { _VIPCondition = value; }
    }
    private int _VIPTimes;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"VIPTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int VIPTimes
    {
      get { return _VIPTimes; }
      set { _VIPTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}