//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillList.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillList")]
  public partial class SkillList : global::ProtoBuf.IExtensible
  {
    public SkillList() {}
    
    private int _skillID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillID
    {
      get { return _skillID; }
      set { _skillID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}