//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillSet")]
  public partial class SkillSet : global::ProtoBuf.IExtensible
  {
    public SkillSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _Factor;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Factor
    {
      get { return _Factor; }
      set { _Factor = value; }
    }
    private int _Count;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private int _AddtionalDamage;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"AddtionalDamage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int AddtionalDamage
    {
      get { return _AddtionalDamage; }
      set { _AddtionalDamage = value; }
    }
    private int _CD;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"CD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int CD
    {
      get { return _CD; }
      set { _CD = value; }
    }
    private int _Gold;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }
    private string _IconID;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"IconID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IconID
    {
      get { return _IconID; }
      set { _IconID = value; }
    }
    private int _randomDamage;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"randomDamage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int randomDamage
    {
      get { return _randomDamage; }
      set { _randomDamage = value; }
    }
    private int _actId;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"actId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actId
    {
      get { return _actId; }
      set { _actId = value; }
    }
    private int _fightCapactiy;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"fightCapactiy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightCapactiy
    {
      get { return _fightCapactiy; }
      set { _fightCapactiy = value; }
    }
    private int _skillUpgradeItemNum;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"skillUpgradeItemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillUpgradeItemNum
    {
      get { return _skillUpgradeItemNum; }
      set { _skillUpgradeItemNum = value; }
    }
    private string _SkillName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillName
    {
      get { return _SkillName; }
      set { _SkillName = value; }
    }
    private int _showSkillId;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"showSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int showSkillId
    {
      get { return _showSkillId; }
      set { _showSkillId = value; }
    }
    private int _Sequence;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Sequence
    {
      get { return _Sequence; }
      set { _Sequence = value; }
    }
    private int _Job;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Job
    {
      get { return _Job; }
      set { _Job = value; }
    }
    private int _UnLockLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"UnLockLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int UnLockLevel
    {
      get { return _UnLockLevel; }
      set { _UnLockLevel = value; }
    }
    private string _SkillDesc;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"SkillDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SkillDesc
    {
      get { return _SkillDesc; }
      set { _SkillDesc = value; }
    }
    private int _SkillClass;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"SkillClass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillClass
    {
      get { return _SkillClass; }
      set { _SkillClass = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}