//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TalkList.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalkList")]
  public partial class TalkList : global::ProtoBuf.IExtensible
  {
    public TalkList() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _talk01;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"talk01", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string talk01
    {
      get { return _talk01; }
      set { _talk01 = value; }
    }
    private int _probability01;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"probability01", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability01
    {
      get { return _probability01; }
      set { _probability01 = value; }
    }
    private string _talk02;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"talk02", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string talk02
    {
      get { return _talk02; }
      set { _talk02 = value; }
    }
    private int _probability02;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"probability02", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability02
    {
      get { return _probability02; }
      set { _probability02 = value; }
    }
    private string _talk03;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"talk03", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string talk03
    {
      get { return _talk03; }
      set { _talk03 = value; }
    }
    private int _probability03;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"probability03", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability03
    {
      get { return _probability03; }
      set { _probability03 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}