//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TenActivityGoldSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenActivityGoldSet")]
  public partial class TenActivityGoldSet : global::ProtoBuf.IExtensible
  {
    public TenActivityGoldSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _dropID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropID
    {
      get { return _dropID; }
      set { _dropID = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _probability;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability
    {
      get { return _probability; }
      set { _probability = value; }
    }
    private int _minLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    private int _maxLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    private int _vipLevel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private int _show;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int show
    {
      get { return _show; }
      set { _show = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}