//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TenActivityMazaiSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenActivityMazaiSet")]
  public partial class TenActivityMazaiSet : global::ProtoBuf.IExtensible
  {
    public TenActivityMazaiSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _mazaiId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mazaiId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mazaiId
    {
      get { return _mazaiId; }
      set { _mazaiId = value; }
    }
    private int _nextId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nextId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextId
    {
      get { return _nextId; }
      set { _nextId = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private string _mazaiName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"mazaiName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mazaiName
    {
      get { return _mazaiName; }
      set { _mazaiName = value; }
    }
    private int _attachProbability;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attachProbability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attachProbability
    {
      get { return _attachProbability; }
      set { _attachProbability = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}