//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TenActivitySpecialSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenActivitySpecialSet")]
  public partial class TenActivitySpecialSet : global::ProtoBuf.IExtensible
  {
    public TenActivitySpecialSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _show;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int show
    {
      get { return _show; }
      set { _show = value; }
    }
    private int _dropCountLimit;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"dropCountLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropCountLimit
    {
      get { return _dropCountLimit; }
      set { _dropCountLimit = value; }
    }
    private int _must;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"must", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int must
    {
      get { return _must; }
      set { _must = value; }
    }
    private int _only;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"only", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int only
    {
      get { return _only; }
      set { _only = value; }
    }
    private int _fristReward;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"fristReward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fristReward
    {
      get { return _fristReward; }
      set { _fristReward = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _dropId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropId
    {
      get { return _dropId; }
      set { _dropId = value; }
    }
    private int _itemId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _probability;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int probability
    {
      get { return _probability; }
      set { _probability = value; }
    }
    private int _minLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int minLevel
    {
      get { return _minLevel; }
      set { _minLevel = value; }
    }
    private int _maxLevel;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"maxLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLevel
    {
      get { return _maxLevel; }
      set { _maxLevel = value; }
    }
    private int _vipLevel;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}