//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TenActivityLuckySet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenActivityLuckySet")]
  public partial class TenActivityLuckySet : global::ProtoBuf.IExtensible
  {
    public TenActivityLuckySet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _nextId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nextId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextId
    {
      get { return _nextId; }
      set { _nextId = value; }
    }
    private int _upperLimit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"upperLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upperLimit
    {
      get { return _upperLimit; }
      set { _upperLimit = value; }
    }
    private int _lowerLimit;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lowerLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lowerLimit
    {
      get { return _lowerLimit; }
      set { _lowerLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}