//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TipAttribute.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TipAttribute")]
  public partial class TipAttribute : global::ProtoBuf.IExtensible
  {
    public TipAttribute() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private string _tip1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tip1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tip1
    {
      get { return _tip1; }
      set { _tip1 = value; }
    }
    private string _tip2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tip2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tip2
    {
      get { return _tip2; }
      set { _tip2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}