//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UiNumItems.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UiNumItems")]
  public partial class UiNumItems : global::ProtoBuf.IExtensible
  {
    public UiNumItems() {}
    
    private int _uiId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uiId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int uiId
    {
      get { return _uiId; }
      set { _uiId = value; }
    }
    private string _titleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"titleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string titleName
    {
      get { return _titleName; }
      set { _titleName = value; }
    }
    private string _info;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}