//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UISet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UISet")]
  public partial class UISet : global::ProtoBuf.IExtensible
  {
    public UISet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type1
    {
      get { return _type1; }
      set { _type1 = value; }
    }
    private int _type2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type2
    {
      get { return _type2; }
      set { _type2 = value; }
    }
    private int _order;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order
    {
      get { return _order; }
      set { _order = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _questID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"questID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questID
    {
      get { return _questID; }
      set { _questID = value; }
    }
    private int _nextOpenSeq;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"nextOpenSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextOpenSeq
    {
      get { return _nextOpenSeq; }
      set { _nextOpenSeq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}