//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UnLockCond.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnLockCond")]
  public partial class UnLockCond : global::ProtoBuf.IExtensible
  {
    public UnLockCond() {}
    
    private int _unlockIf;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"unlockIf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockIf
    {
      get { return _unlockIf; }
      set { _unlockIf = value; }
    }
    private int _unlockParam;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"unlockParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unlockParam
    {
      get { return _unlockParam; }
      set { _unlockParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}