//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UnlockTimeGroup.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnlockTimeGroup")]
  public partial class UnlockTimeGroup : global::ProtoBuf.IExtensible
  {
    public UnlockTimeGroup() {}
    
    private int _day;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private int _startHour;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startHour
    {
      get { return _startHour; }
      set { _startHour = value; }
    }
    private int _startMinute;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startMinute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startMinute
    {
      get { return _startMinute; }
      set { _startMinute = value; }
    }
    private int _endHour;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"endHour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endHour
    {
      get { return _endHour; }
      set { _endHour = value; }
    }
    private int _endMinute;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"endMinute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endMinute
    {
      get { return _endMinute; }
      set { _endMinute = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}