//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VIPResetSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VIPResetSet")]
  public partial class VIPResetSet : global::ProtoBuf.IExtensible
  {
    public VIPResetSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _liemingReset;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"liemingReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int liemingReset
    {
      get { return _liemingReset; }
      set { _liemingReset = value; }
    }
    private int _reliveGold;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"reliveGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reliveGold
    {
      get { return _reliveGold; }
      set { _reliveGold = value; }
    }
    private int _eliteReset;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"eliteReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eliteReset
    {
      get { return _eliteReset; }
      set { _eliteReset = value; }
    }
    private int _multiRaidReset;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"multiRaidReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int multiRaidReset
    {
      get { return _multiRaidReset; }
      set { _multiRaidReset = value; }
    }
    private int _bossRaidReset;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"bossRaidReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bossRaidReset
    {
      get { return _bossRaidReset; }
      set { _bossRaidReset = value; }
    }
    private int _pvpReset;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pvpReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pvpReset
    {
      get { return _pvpReset; }
      set { _pvpReset = value; }
    }
    private int _goldReset;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"goldReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldReset
    {
      get { return _goldReset; }
      set { _goldReset = value; }
    }
    private int _strengthReset;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"strengthReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strengthReset
    {
      get { return _strengthReset; }
      set { _strengthReset = value; }
    }
    private int _anabasisReset;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"anabasisReset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anabasisReset
    {
      get { return _anabasisReset; }
      set { _anabasisReset = value; }
    }
    private int _reliveDiamond;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"reliveDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reliveDiamond
    {
      get { return _reliveDiamond; }
      set { _reliveDiamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}