//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: VIPSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VIPSet")]
  public partial class VIPSet : global::ProtoBuf.IExtensible
  {
    public VIPSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _activityResetNum;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"activityResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityResetNum
    {
      get { return _activityResetNum; }
      set { _activityResetNum = value; }
    }
    private int _teamResetNum;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"teamResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamResetNum
    {
      get { return _teamResetNum; }
      set { _teamResetNum = value; }
    }
    private int _bossResetNum;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"bossResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bossResetNum
    {
      get { return _bossResetNum; }
      set { _bossResetNum = value; }
    }
    private int _towerResetNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"towerResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int towerResetNum
    {
      get { return _towerResetNum; }
      set { _towerResetNum = value; }
    }
    private int _arenaResetNum;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"arenaResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arenaResetNum
    {
      get { return _arenaResetNum; }
      set { _arenaResetNum = value; }
    }
    private int _reliveNum;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"reliveNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reliveNum
    {
      get { return _reliveNum; }
      set { _reliveNum = value; }
    }
    private int _anabasisResetNum;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"anabasisResetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int anabasisResetNum
    {
      get { return _anabasisResetNum; }
      set { _anabasisResetNum = value; }
    }
    private float _anabasisRewardFactor;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"anabasisRewardFactor", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float anabasisRewardFactor
    {
      get { return _anabasisRewardFactor; }
      set { _anabasisRewardFactor = value; }
    }
    private int _goldenTouchNum;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"goldenTouchNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int goldenTouchNum
    {
      get { return _goldenTouchNum; }
      set { _goldenTouchNum = value; }
    }
    private int _handMidasMulti;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"handMidasMulti", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int handMidasMulti
    {
      get { return _handMidasMulti; }
      set { _handMidasMulti = value; }
    }
    private int _vipExp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"vipExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipExp
    {
      get { return _vipExp; }
      set { _vipExp = value; }
    }
    private int _powerNum;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"powerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int powerNum
    {
      get { return _powerNum; }
      set { _powerNum = value; }
    }
    private int _strengthen;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"strengthen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strengthen
    {
      get { return _strengthen; }
      set { _strengthen = value; }
    }
    private int _sweepOneTime;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"sweepOneTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sweepOneTime
    {
      get { return _sweepOneTime; }
      set { _sweepOneTime = value; }
    }
    private int _sweepTenTimes;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"sweepTenTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sweepTenTimes
    {
      get { return _sweepTenTimes; }
      set { _sweepTenTimes = value; }
    }
    private int _actSweepOneTime;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"actSweepOneTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actSweepOneTime
    {
      get { return _actSweepOneTime; }
      set { _actSweepOneTime = value; }
    }
    private int _actSweepTenTimes;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"actSweepTenTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actSweepTenTimes
    {
      get { return _actSweepTenTimes; }
      set { _actSweepTenTimes = value; }
    }
    private int _vipShop;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"vipShop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipShop
    {
      get { return _vipShop; }
      set { _vipShop = value; }
    }
    private int _lieming;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"lieming", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lieming
    {
      get { return _lieming; }
      set { _lieming = value; }
    }
    private int _sell;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"sell", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sell
    {
      get { return _sell; }
      set { _sell = value; }
    }
    private int _pickup;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"pickup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pickup
    {
      get { return _pickup; }
      set { _pickup = value; }
    }
    private int _vipYuanJia;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"vipYuanJia", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipYuanJia
    {
      get { return _vipYuanJia; }
      set { _vipYuanJia = value; }
    }
    private int _lieMingID;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"lieMingID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lieMingID
    {
      get { return _lieMingID; }
      set { _lieMingID = value; }
    }
    private int _zhuizhaiBuyCount;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"zhuizhaiBuyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zhuizhaiBuyCount
    {
      get { return _zhuizhaiBuyCount; }
      set { _zhuizhaiBuyCount = value; }
    }
    private int _dropID;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"dropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dropID
    {
      get { return _dropID; }
      set { _dropID = value; }
    }
    private int _giftid;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"giftid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int giftid
    {
      get { return _giftid; }
      set { _giftid = value; }
    }
    private int _maxFriend;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"maxFriend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxFriend
    {
      get { return _maxFriend; }
      set { _maxFriend = value; }
    }
    private int _userPowerProp;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"userPowerProp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userPowerProp
    {
      get { return _userPowerProp; }
      set { _userPowerProp = value; }
    }
    private int _vipGiftPrice;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vipGiftPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vipGiftPrice
    {
      get { return _vipGiftPrice; }
      set { _vipGiftPrice = value; }
    }
    private float _expAddition;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"expAddition", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float expAddition
    {
      get { return _expAddition; }
      set { _expAddition = value; }
    }
    private float _goldAddition;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"goldAddition", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float goldAddition
    {
      get { return _goldAddition; }
      set { _goldAddition = value; }
    }
    private float _activityCD;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"activityCD", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float activityCD
    {
      get { return _activityCD; }
      set { _activityCD = value; }
    }
    private float _arenaCD;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"arenaCD", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float arenaCD
    {
      get { return _arenaCD; }
      set { _arenaCD = value; }
    }
    private int _eliteNum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"eliteNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int eliteNum
    {
      get { return _eliteNum; }
      set { _eliteNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}