//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WingSet.proto
// Note: requires additional types generated from: WingAttr.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WingSet")]
  public partial class WingSet : global::ProtoBuf.IExtensible
  {
    public WingSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private readonly global::System.Collections.Generic.List<WingAttr> _attr = new global::System.Collections.Generic.List<WingAttr>();
    [global::ProtoBuf.ProtoMember(10, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WingAttr> attr
    {
      get { return _attr; }
    }
  
    private string _wingName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wingName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string wingName
    {
      get { return _wingName; }
      set { _wingName = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _wingExp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"wingExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wingExp
    {
      get { return _wingExp; }
      set { _wingExp = value; }
    }
    private int _maxLv;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxLv
    {
      get { return _maxLv; }
      set { _maxLv = value; }
    }
    private string _iconId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"iconId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string iconId
    {
      get { return _iconId; }
      set { _iconId = value; }
    }
    private int _conditions;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"conditions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int conditions
    {
      get { return _conditions; }
      set { _conditions = value; }
    }
    private int _params;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"params", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int @params
    {
      get { return _params; }
      set { _params = value; }
    }
    private int _attrNum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"attrNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attrNum
    {
      get { return _attrNum; }
      set { _attrNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}