//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ZhuizhaiSet.proto
namespace Excel2Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZhuizhaiSet")]
  public partial class ZhuizhaiSet : global::ProtoBuf.IExtensible
  {
    public ZhuizhaiSet() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private int _num2;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"num2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num2
    {
      get { return _num2; }
      set { _num2 = value; }
    }
    private int _item3;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"item3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item3
    {
      get { return _item3; }
      set { _item3 = value; }
    }
    private int _num3;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"num3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num3
    {
      get { return _num3; }
      set { _num3 = value; }
    }
    private int _upOdds;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"upOdds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int upOdds
    {
      get { return _upOdds; }
      set { _upOdds = value; }
    }
    private int _downOdds;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"downOdds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int downOdds
    {
      get { return _downOdds; }
      set { _downOdds = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _quality;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _item1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"item1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item1
    {
      get { return _item1; }
      set { _item1 = value; }
    }
    private int _num1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"num1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num1
    {
      get { return _num1; }
      set { _num1 = value; }
    }
    private int _item2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"item2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item2
    {
      get { return _item2; }
      set { _item2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}